# Generated by Django 5.0.6 on 2024-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_add_employeedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_PayrollDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refno', models.CharField(default='', max_length=500)),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('payroll_status', models.CharField(default='Active', max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
