# Generated by Django 5.0.6 on 2024-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_add_payrolldb'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_employeedb',
            name='emp_img',
            field=models.ImageField(default=' ', upload_to='emp_img'),
        ),
    ]
