# Generated by Django 5.0.6 on 2024-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_add_employeedb_emp_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_AttendanceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('emp_no', models.PositiveBigIntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
