# Generated by Django 5.0.6 on 2024-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_add_attendancedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_attendancedb',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
