# Generated by Django 5.0.6 on 2024-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_add_attendancedb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_db',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
