# Generated by Django 5.0.6 on 2024-07-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_add_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Department',
            new_name='Add_DepartmentDB',
        ),
    ]
