# Generated by Django 5.0.6 on 2024-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_rename_add_department_add_departmentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_departmentdb',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
